version: "3.9"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

  app:
    image: eagle-tranz-server:1.0
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    container_name: eagle-tranz-server

volumes:
  mongo_data:
